[package]
name = "pwbox"
version = "0.1.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
license = "Apache-2.0"
keywords = ["cryptography", "encryption", "password-based", "exonum"]
categories = ["cryptography"]
description = "Modular password-based encryption"

[dependencies]
rand_core = "=0.3.0"
clear_on_drop = "=0.2.3"
constant_time_eq = "=0.1.3"
smallvec = "=0.6.6"
failure = "0.1.5"
failure_derive = "0.1.5"
# serialization-related dependencies
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hex-buffer-serde = "=0.1.1"
# crypto backends
exonum_sodiumoxide = { version = "=0.0.20", optional = true }
rust-crypto = { version = "=0.2.36", optional = true }

[dev-dependencies]
serde_cbor = "0.9.0"
hex = "=0.3.2"
rand = "=0.6.1"
assert_matches = "1.3.0"
serde_yaml = "0.8.7"
toml = "=0.4.9"

[features]
default = ["exonum_sodiumoxide"]

[[test]]
name = "serialization"
path = "tests/serialization.rs"
required-features = ["rust-crypto", "exonum_sodiumoxide"]

[[example]]
name = "sodium_keypair"
path = "examples/sodium_keypair.rs"
required-features = ["exonum_sodiumoxide"]
